project:
  type: book
  output-dir: docs

book:
  title: "Documentação do Painel Gerencial CIGA"
  date: "1/24/2025"
  chapters:
    - index.qmd
    - ambientes.qmd
    - acesso.qmd
    - paineis.qmd
    - relatorio.qmd
    - repositorios.qmd
    - bancos_de_dados.qmd
    - actions.qmd
    - shiny_server.qmd

bibliography: references.bib

format:
  html:
    fig-cap-location: bottom
  # pdf:
  #   documentclass: scrreprt
theme:
  light: flatly
  dark: superhero

lang: pt
language:
  title-block-author-single: "Autoria"
  title-block-published: "Atualizado em"
  crossref-ch-prefix: "Seção"
