project:
  type: book

book:
  title: "Documentação do Painel CIGA-MPMG"
  author: "R6"
  date: "5/24/2024"
  chapters:
    - index.qmd
    - ambientes.qmd
    - acesso.qmd
    - paineis.qmd
    - relatorio.qmd
    - repositorios.qmd
    - actions.qmd
    - shiny_server.qmd
    # - bancos-de-dados.qmd
    # - workflows.qmd
    # - referencias.qmd
    # - casos_de_uso.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-cap-location: bottom
  # pdf:
  #   documentclass: scrreprt

editor: visual

lang: pt
language: 
  title-block-author-single: "Autoria"
  title-block-published: "Atualizado em"
  crossref-ch-prefix: "Seção"
