project:
  type: book

book:
  title: "Documentação do Painel Gerencial CIGA"
  #author: "R6"
  date: "1/24/2025"
  chapters:
    - index.qmd
    - ambientes.qmd
    - acesso.qmd
    - paineis.qmd
    - relatorio.qmd
    - repositorios.qmd
    - actions.qmd
    - shiny_server.qmd
    # - bancos-de-dados.qmd
    # - workflows.qmd
    # - referencias.qmd
    # - casos_de_uso.qmd

bibliography: references.bib

format:
  html:
    fig-cap-location: bottom
  # pdf:
  #   documentclass: scrreprt
editor: visual
theme:
  light: flatly
  dark: superhero

lang: pt
language:
  title-block-author-single: "Autoria"
  title-block-published: "Atualizado em"
  crossref-ch-prefix: "Seção"
