# Repositórios {#sec-repositorios}

Nesta seção, listamos e descrevemos todos os repositórios utilizados pelo Painel Gerencial CIGA-MPMG.

## painelMain

-   **Descrição**: contém o código-fonte da home do Painel Gerencial CIGA-MPMG (@sec-painel-home), a página acessada logo após o login.

-   **Link**: <https://github.com/ciga-mpmg/painelMain>

-   **Actions**: possui os Actions de deploy em homologação e produção de cada um dos painéis e para gerar os relatórios gerenciais.

## painelBarragens

-   **Descrição**: contém o código-fonte do painel Barragens (@sec-painel-barragens).

-   **Link**: <https://github.com/ciga-mpmg/painelBarragens>

-   **Actions**: não possui.

## painelInfoTacs

-   **Descrição**: contém o código-fonte do painel Informações sobre os TACs (@sec-painel-infoTacs).

-   **Link**: <https://github.com/ciga-mpmg/painelInfoTacs>

-   **Actions**: não possui.

## painelDescaracterizacao

-   **Descrição**: contém o código-fonte do painel Descaracterização (@sec-painel-descaracterizacao).

-   **Link**: <https://github.com/ciga-mpmg/painelDescaracterizacao>

-   **Actions**: não possui.

## painelRecomendacoes

-   **Descrição**: contém o código-fonte do painel Recomendações (@sec-painel-recomendacoes).

-   **Link**: <https://github.com/ciga-mpmg/painelRecomendacoes>

-   **Actions**: não possui.

## painelAssets

-   **Descrição**: contém o código-fonte de um pacote R com funções auxiliares utilizadas em todos os painéis.

-   **Link**: <https://github.com/ciga-mpmg/painelAssets>

-   **Actions**: não possui.

## painelLogin

-   **Descrição**: contém o código-fonte de um pacote R com funções utilizadas na construção da camada de login via Firebase de cada Painel. Também possui o front-end da tela de Login.

-   **Link**: <https://github.com/ciga-mpmg/painelLogin>

-   **Actions**: não possui.

## painelRelatorioGerencial

-   **Descrição**: contém o código-fonte de todas as versões do Relatório Gerencial.

-   **Link**: <https://github.com/ciga-mpmg/painelRelatorioGerencial>

-   **Actions**: não possui.

## painelActions

-   **Descrição**: contém uma descrição de todas as automações em Github Actions, suas localizações e seus respectivos impactos no sistema. Nesse repositório também listamos os requisitos e criticidades de cada automação.

-   **Link**: <https://github.com/ciga-mpmg/painelActions>

-   **Actions**: não possui.

## painelDocumentacao

-   **Descrição**: contém os arquivos que compõem esta documentação.

-   **Link**: <https://github.com/ciga-mpmg/painelDocumentacao>

-   **Actions**: não possui.

## scraper_sigbm

-   **Descrição**: contém os códigos fonte de acesso ao SIGBM e atualização dos bancos de dados de homologação e produção com os seus conteúdos e consolidações de informação de recomendações.

-   **Link**: <https://github.com/ciga-mpmg/scraper_sigbm>

-   **Actions**: download_sigbm. Essa automação é responsável por atualizar as informações do SIGBM nos bancos de dados, além de consolidar informações oriundas do Sistema de Cadastro de TACs e do SISVAR.

## download_IDE_SISEMA

-   **Descrição**: faz download dos dados do IDE SISEMA.

-   **Link**: <https://github.com/ciga-mpmg/download_IDE_SISEMA>

-   **Actions**: download dos dados do IDE Sisema acessando o seu Web Map Server (WMS).


## googleStorageMetadata

-   **Descrição**: importa informações de arquivos que estão no Google Cloud Storage.

-   **Link**: <https://github.com/ciga-mpmg/googleStorageMetadata>

-   **Actions**: importa informações de arquivos que estão no Google Cloud Storage, como documentos dos TACs, relatórios gerenciais, imagens de satélite e as máscaras das imagens de satélite.


## resuvafeca

-   **Descrição**: Repositório do código do programa de processo cíclico do CIGA referente à REquisição-SUbmissão-VAlidação-FEedback-CArga.

-   **Link**: <https://github.com/ciga-mpmg/resuvafeca>

- **Actions**: sempre que houver novas alterações na branch main do repositório resuvafeca, ativa os seguintes workflows:
   - [update-sigbm.yaml](https://github.com/ciga-mpmg/scraper_sigbm/actions/workflows/update-sigbm.yaml) –
    atualizar sigbm
   - [ciga-mpmg/relatorioGerencial](https://github.com/ciga-mpmg/relatorioGerencial) –
    gerar relatório gerencial.

## comarcasTJMG

-   **Descrição**: pacote que visa facilitar a obtenção de informação relacionada às comarcas do TJMG em relação aos municípios do estado de Minas Gerais.

-   **Link**: <https://github.com/tech-legado/comarcasTJMG>

-   **Actions**: não possui.


## download_comarcas_TJMG

-   **Descrição**: web scraper responsável por raspar dados das comarcas do TJMG disponíveis em pdf no site do Tribunal.

-   **Link**: <https://github.com/ciga-mpmg/download_comarcas_TJMG/>

-   **Actions**: faz download do pdf dos municípios e comarcas do Tribunal de Justiça do estado de Minas Gerais


## sigbm-mapa-inundacao

-   **Descrição**: executa a raspagem do [mapa de inundação de barragens cadastradas no  SIGBM](https://app.anm.gov.br/SIGBM/Publico/GerenciarPublico).

-   **Link**: <https://github.com/ciga-mpmg/sigbm-mapa-inundacao>

-   **Actions**: faz o download dos mapas de inundação disponibilizados no portal [SIGBM](https://app.anm.gov.br/SIGBM/Publico/ClassificacaoNacionalDaBarragem) e o upload para o Google Cloud Storage.
